
DROP TABLE IF EXISTS USER_NOTIFICATION_ENTITY;
  
CREATE TABLE USER_NOTIFICATION_ENTITY (
  notification_id long AUTO_INCREMENT  PRIMARY KEY,
  user_id VARCHAR(250) NOT NULL,
  notification_details VARCHAR(250) NOT NULL
);